# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
              [[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]],
              [[10, 11, 12], 
               [13, 14, 15], 
               [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones

np.ones(shape=(10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros

np.zeros(shape=(7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7, 2))

array([[5, 9],
       [0, 3],
       [6, 4],
       [4, 7],
       [6, 0],
       [8, 6],
       [1, 4]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.1663676 , 0.57329794, 0.48096566, 0.25469741, 0.33410021],
       [0.33672535, 0.02541942, 0.89677212, 0.72807685, 0.48162824],
       [0.03043287, 0.87239587, 0.82814512, 0.51752172, 0.82205109]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_arr = np.random.randint(10, size=(3, 7))
# Find the unique numbers in the array you just created
np.unique(random_arr)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
random_arr[0]

array([8, 0, 9, 2, 6, 3, 8])

In [15]:
# Get the first 2 rows of latest array you created
random_arr[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[0][:2], random_arr[1][:2]

(array([8, 0]), array([2, 4]))

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_num = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [18]:
random_num

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [19]:
# Add the two arrays together
random_num + ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [20]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5, 3))

In [21]:
# Try add the array of ones and the other most recent array together
random_num + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [28]:
# Create another array of ones of shape (3, 5)
x_arr = np.random.random(size=(3, 5))

In [29]:
# Subtract the new array of ones from the other most recent array
x_arr - random_num

array([[-3.43229967, -0.96868671, -2.15771523, -5.55024587, -6.60484976],
       [-1.07334113,  0.727272  , -2.67345923, -0.42955603, -6.47916574],
       [-2.03882798, -0.15546615, -4.25267989, -4.46030787, -8.41324883]])

In [30]:
# Multiply the ones array with the latest array
x_arr * ones

array([[0.56770033, 0.03131329, 0.84228477, 0.44975413, 0.39515024],
       [0.92665887, 0.727272  , 0.32654077, 0.57044397, 0.52083426],
       [0.96117202, 0.84453385, 0.74732011, 0.53969213, 0.58675117]])

In [31]:
# Take the latest array to the power of 2 using '**'
x_arr ** 2

array([[0.32228366, 0.00098052, 0.70944364, 0.20227878, 0.15614371],
       [0.85869665, 0.52892456, 0.10662887, 0.32540633, 0.27126833],
       [0.92385166, 0.71323742, 0.55848735, 0.2912676 , 0.34427693]])

In [32]:
# Do the same thing with np.square()
np.square(x_arr)

array([[0.32228366, 0.00098052, 0.70944364, 0.20227878, 0.15614371],
       [0.85869665, 0.52892456, 0.10662887, 0.32540633, 0.27126833],
       [0.92385166, 0.71323742, 0.55848735, 0.2912676 , 0.34427693]])

In [33]:
# Find the mean of the latest array using np.mean()
np.mean(x_arr)

0.6024947940231474

In [34]:
# Find the maximum of the latest array using np.max()
np.max(x_arr)

0.9611720243493491

In [35]:
# Find the minimum of the latest array using np.min()
np.min(x_arr)

0.03131329245555858

In [36]:
# Find the standard deviation of the latest array
np.std(x_arr)

0.24057935043325462

In [37]:
# Find the variance of the latest array
np.var(x_arr)

0.057878423854886736

In [38]:
# Reshape the latest array to (3, 5, 1)
x_arr.reshape(3, 5, 1)

array([[[0.56770033],
        [0.03131329],
        [0.84228477],
        [0.44975413],
        [0.39515024]],

       [[0.92665887],
        [0.727272  ],
        [0.32654077],
        [0.57044397],
        [0.52083426]],

       [[0.96117202],
        [0.84453385],
        [0.74732011],
        [0.53969213],
        [0.58675117]]])

In [39]:
# Transpose the latest array
x_arr.reshape(3, 5, 1).T

array([[[0.56770033, 0.92665887, 0.96117202],
        [0.03131329, 0.727272  , 0.84453385],
        [0.84228477, 0.32654077, 0.74732011],
        [0.44975413, 0.57044397, 0.53969213],
        [0.39515024, 0.52083426, 0.58675117]]])

What does the transpose do?

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_1 = np.random.randint(10, size=(3, 3))
arr_2 = np.random.randint(10, size=(3, 2))


In [41]:
arr_1

array([[8, 8, 0],
       [8, 6, 8],
       [7, 0, 7]])

In [42]:
arr_2

array([[7, 2],
       [0, 7],
       [2, 2]])

In [43]:
# Perform a dot product on the two newest arrays you created
arr_1.dot(arr_2)

array([[56, 72],
       [72, 74],
       [63, 28]])

In [44]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_1 = np.random.randint(10, size=(4, 3))
arr_2 = np.random.randint(10, size=(4, 3))

In [45]:
# Perform a dot product on the two newest arrays you created
arr_1.dot(arr_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [47]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr_1.dot(arr_2.T)

array([[ 64,  73,  18,   8],
       [131, 115,  28,  42],
       [120, 103,  26,  40],
       [ 30,  32,  14,   4]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [49]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_1 = np.random.randint(10, size=(2, 2))
array_2 = np.random.randint(10, size=(2, 2))

In [50]:
# Compare the two arrays with '>'
array_1 > array_2

array([[ True,  True],
       [ True, False]])

In [51]:
array_1

array([[8, 9],
       [9, 2]])

In [52]:
array_2

array([[6, 0],
       [3, 3]])

What happens when you compare the arrays with `>`?

In [53]:
# Compare the two arrays with '>='
array_1 >= array_2

array([[ True,  True],
       [ True, False]])

In [54]:
# Find which elements of the first array are greater than 7
array_1 > 7

array([[ True,  True],
       [ True, False]])

In [55]:
# Which parts of each array are equal? (try using '==')
array_1 == array_2

array([[False, False],
       [False, False]])

In [59]:
# Sort one of the arrays you just created in ascending order
np.sort(array_1)

array([[8, 9],
       [2, 9]])

In [60]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_1)

array([[0, 1],
       [1, 0]], dtype=int64)

In [62]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_1)

1

In [64]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_1)

3

In [65]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_1, axis=1)

array([1, 0], dtype=int64)

In [66]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_1, axis=0)

array([0, 1], dtype=int64)

In [73]:
# Create an array of normally distributed random numbers
z_arr = np.random.randn(3, 5)
z_arr

array([[-1.91877122, -0.02651388,  0.06023021,  2.46324211, -0.19236096],
       [ 0.30154734, -0.03471177, -1.16867804,  1.14282281,  0.75193303],
       [ 0.79103195, -0.90938745,  1.40279431, -1.40185106,  0.58685709]])

In [71]:
# Create an array with 10 evenly spaced numbers between 1 and 100
y_arr = np.arange(0, 100, 10)
y_arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.