In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2, 3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [27]:
random_array

array([[4, 3, 5, 4, 8],
       [5, 1, 5, 8, 4],
       [1, 6, 2, 7, 4]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.64097677, 0.53181886, 0.1388545 ],
       [0.19679288, 0.28670097, 0.10431961],
       [0.42457219, 0.35276298, 0.42573453],
       [0.97086546, 0.25713042, 0.00259688],
       [0.27269211, 0.98834061, 0.15085275]])

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[7.21684617e-04, 2.41876276e-01, 1.12085941e-01],
       [5.26171147e-01, 9.63410742e-01, 3.16293592e-02],
       [3.60737756e-01, 6.09665021e-01, 6.34842627e-01],
       [8.19103993e-01, 1.17001209e-02, 7.15581790e-01],
       [6.69567805e-01, 4.88697346e-01, 7.48153481e-01]])

In [33]:
# Pseudo-random numbers
# np.random.seed(seed=0)
import numpy as np
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[9, 7, 7],
       [9, 9, 2],
       [1, 4, 8],
       [1, 6, 4],
       [1, 7, 5]])

In [34]:
random_array_4.shape

(5, 3)

In [35]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [36]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [37]:
random_array_5.shape

(5, 3)

## 3. Viewing arrays and matrices

In [38]:
random_array_4

array([[9, 7, 7],
       [9, 9, 2],
       [1, 4, 8],
       [1, 6, 4],
       [1, 7, 5]])

In [39]:
np.unique(random_array_4)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [40]:
a1[0]

1

In [41]:
a2[0][1]

2.0

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a2[1]

array([4. , 5. , 6.5])

In [46]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [48]:
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [49]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [50]:
# Get the first 4 number of the inner most arrays

In [51]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [53]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [54]:
a1 + ones

array([2., 3., 4.])

In [55]:
a1 - ones

array([0., 1., 2.])

In [56]:
a1 * ones

array([1., 2., 3.])

In [57]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [58]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [59]:
x * a3

NameError: name 'x' is not defined

In [ ]:
a3

In [ ]:
a1 * a3

In [ ]:
x = a2.reshape(2, 1, 3)
x

In [ ]:
a1 / ones

In [ ]:
# Floor division rounds down the decimals(removes spaces after decimal)
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 + ones

In [ ]:
a1 % 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]

In [ ]:
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on Numpy arrays (`np.sum()`)

In [ ]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = sqrt of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

high_var_array.mean()

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

In [ ]:
data = np.array([1, 100, 200, 300, 4000, 5000])
mean = np.mean(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

### Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a3.shape

In [ ]:
a2_reshape.shape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
# Transpose = switches the axis'
a2.T

In [ ]:
a2.shape

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

### Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
mat2.T.shape

In [ ]:
np.dot(mat1, mat2.T)

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

In [60]:
## Website to get a visual look at multiplying matrices/dot product: http://matrixmultiplication.xyz/

## Dot product example (nut butter sales)

In [62]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [90]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                           index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [66]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [68]:
prices.shape

(3,)

In [69]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [74]:
prices.shape

(3,)

In [73]:
sales_amounts.shape

(5, 3)

In [71]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [92]:
# Shape aren't aligned, let's transpose
total_sales = butter_prices.dot(weekly_sales.T)
total_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [94]:
total_sales.shape

(1, 5)

In [83]:
sales_amounts.T.shape

(3, 5)

In [95]:
weekly_sales["Total ($)"] = total_sales.T

In [96]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison Operators


In [97]:
a1

array([1, 2, 3])

In [98]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [99]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [103]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [102]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [104]:
a1 > 5

array([False, False, False])

In [105]:
a1 < 5

array([ True,  True,  True])

In [106]:
a1 == a1

array([ True,  True,  True])

In [108]:
a1

array([1, 2, 3])

In [109]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [107]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting array

In [111]:
random_array = np.random.randint(10, size=(3,5))

In [117]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [113]:
random_array.shape

(3, 5)

In [114]:
np.sort(random_array)


array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [116]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [118]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [119]:
a1

array([1, 2, 3])

In [120]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [121]:
np.argmin(a1)

0

In [122]:
np.argmax(a1)

2

In [123]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [125]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [127]:
np.argmax(random_array, axis=1)

array([4, 1, 1], dtype=int64)

### 6. Practical Example - NumPy in Action!!!

<img src="images/panda.png"/>

In [131]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [133]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [135]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [137]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [139]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src="images/dog-photo.png"/>

In [140]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [141]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)